from django.urls import path
from accounts import views

urlpatterns = [
 	path('', views.index, name='index'),
	path('login', views.login, name='login'),
	path('signup', views.signup, name='signup'),
	path('logout', views.logout, name='logout'),
	path('home',views.home,name='home' ),
	path('contact_form',views.contact_form,name='contact_form'),
	path('bookticket',views.bookticket,name='bookticket'),
	path('ticket_pur/<token>/',views.ticket_pur,name='ticket_pur'),
	path('pdf_download/<token>/',views.pdf_download,name='pdf_download'),
	path('ratings',views.ratings,name='ratings'),
	# path('changepassword', views.changepassword, name='changepassword'),
	path('newsfeed', views.newsfeed, name='newsfeed'),
	path('seatbook', views.seatbook, name='seatbook'),
	path('ticket', views.ticket, name='ticket'),
	path('show_pur_ticket', views.show_pur_ticket, name='show_pur_ticket'),
	path('pur', views.pur, name='pur'),
	path('viewprofile', views.viewprofile, name='viewprofile'),
	path('editprofile', views.editprofile, name='editprofile'),
	path('pdf', views.pdf, name='pdf'),
	path('discount', views.discount, name='discount'),
	path('covidloss', views.covidloss, name='covidloss'),
	path('news3', views.news3, name='news3'),
	path('new4', views.new4, name='new4'),
	path('about_us', views.about_us, name='about_us'),
	path('adminpanel', views.adminpanel, name='adminpanel'),
	path('accountslist',views.accountslist,name='accountslist'),
	path('trainslist',views.trainslist,name='trainslist'),
	path('routeslist',views.routeslist,name='routeslist'),
	path('reservation_list',views.reservation_list,name='reservation_list'),
	path('purchaselists',views.purchaselists,name='purchaselists'),
	path('reset-password', views.reset_password, name='reset-password'),
    path('change-password/<token>/', views.change_password, name='change-password'),
]
