# Generated by Django 2.1.3 on 2022-01-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='msgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=20)),
                ('person_email', models.CharField(max_length=20)),
                ('person_contact', models.IntegerField(max_length=11)),
                ('msg', models.CharField(max_length=1000)),
            ],
        ),
    ]
